---

name: "monitoring"

services:
    worker:
        container_name: "monitoring-worker"
        image: "akeb/monitoring-worker:dev"
        restart: unless-stopped
        build: .
        env_file:
            - .env
        volumes:
           - ./src:/app
           - ./logs/php/:/var/log/php/:rw
        extra_hosts:
           - "monitoring.test:192.168.3.9"
           - "monitoring.test:192.168.3.4"

