---

name: "monitoring"

services:
    worker:
        container_name: "monitoring-worker"
        image: "akeb/monitoring-worker:dev"
        restart: unless-stopped
        build: .
        volumes:
            - ./src/lib:/app/lib
            - ./src/main.php:/app/main.php
            - ./src/composer.json:/app/composer.json
        environment:
            - SERVER_HOST=${SERVER_HOST}
            - WORKER_NAME=${WORKER_NAME}

